name: Build

on:
  push:
    branches-ignore:
      - "gh-pages"
    paths-ignore:
      - ".github/workflows/**"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Verify Format
        run: dotnet format --verify-no-changes
  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Set up dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Print environment
        run: |
          dotnet --info
          nuget help | grep Version
          echo "Github ref: $GITHUB_REF"
          echo "Github event: $GITHUB_EVENT"
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Restore dependencies
        run: dotnet restore --locked-mode

      - name: Build solution
        run: dotnet build SimpleRedirects.sln --configuration Debug

      - name: Run tests
        run: dotnet test SimpleRedirects.sln --configuration Debug --logger "trx;LogFileName=sr-test-results.trx"

      - name: Report test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Results
          path: "**/*-test-results.trx"
          reporter: dotnet-trx
          fail-on-error: true
          list-suites: "all"
          list-tests: "all"
          max-annotations: "10"
